{% set version = "2026.7-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gparotation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GPArotation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GPArotation/GPArotation_{{ version }}.tar.gz
  sha256: 8802a636005fa1d9afea11898960a574e628155edf02e63ea27ebc2d84ebe6fc

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('GPArotation')"           # [not win]
    - "\"%R%\" -e \"library('GPArotation')\""  # [win]

about:
  home: https://cran.r-project.org/package=GPArotation
  license: GPL-2.0-or-later
  summary: Gradient projection algorithms for orthogonal and oblique rotation of factor loadings matrices in factor analysis. Implements a comprehensive set of rotation criteria including quartimax, quartimin, oblimin, geomin, simplimax, the Crawford-Ferguson family, and target rotation, among others. Supports multiple
    random starts. For details see Bernaards and Jennrich (2005) <doi:10.1177/0013164404272507>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
